name: Tests (Apple Silicon)

on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    # strategy:
    #   neovim: [nightly, v0.9.2, v0.8.3]
    uses: elixir-tools/private-workflows/.github/workflows/ci.yaml@f994f37f3587cf59e9305d69391a541a7551875a
    with:
      repo: elixir-tools/elixir-tools.nvim
      args: -e URL="https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
