name: Tests (Apple Silicon)

on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: unit tests
    strategy:
      neovim: [nightly, v0.9.2, v0.8.3]
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)
    uses: elixir-tools/private-workflows/.github/workflows/ci.yaml@main
    with:
      repo: elixir-tools/next-ls
      args: -e URL="https://github.com/neovim/neovim/releases/download/${{ matrix.neovim }}/nvim-macos.tar.gz"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
