name: Tests (Apple Silicon)

on: [push, pull_request]
concurrency:
  group: apple-silicon-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)
    strategy:
      matrix:
        neovim: [nightly, v0.9.2, v0.8.3]
    uses: elixir-tools/private-workflows/.github/workflows/ci.yaml@main
    with:
      name: unit tests
      repo: elixir-tools/elixir-tools.nvim
      args: -e URL="https://github.com/neovim/neovim/releases/download/${{ matrix.neovim }}/nvim-macos.tar.gz"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
