name: Tests

on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stylua:
    name: Stylua
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  tests:
    name: tests (${{ matrix.os }} - ${{ matrix.nvim-version }})
    runs-on: ${{ matrix.os }}

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        nvim-version: [v0.8.3, v0.9.5, v0.10.3, v0.11.2]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc
      - uses: DeterminateSystems/magic-nix-cache-action@03659f4394aec2317771e29041ef266669e2ee12
      - uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6.1.0
      - name: Run nvim-test tests
        run: nix shell nixpkgs#bash nixpkgs#just -c just test ${{ matrix.nvim-version }}
