name: panvimdoc
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    name: vimdoc generator
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: elixir-tools.nvim
          version: "NVIM v0.8.0"
          demojify: true
          treesitter: true

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
